# Generated by Django 5.1.6 on 2025-02-12 17:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], default='operador', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
