# Generated by Django 5.1.6 on 2025-02-12 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_customuser_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
