# Generated by Django 5.1.6 on 2025-02-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_data_cadastro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_compra',
        ),
    ]
