# Generated by Django 5.1.6 on 2025-02-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_rename_preco_produto_preco_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_compra',
            new_name='preco',
        ),
    ]
